# Generated by Django 4.2.6 on 2023-10-17 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventproject.events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=eventproject.events.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
