# Generated by Django 4.2.6 on 2023-10-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='user',
        ),
    ]
