# Generated by Django 4.2.6 on 2023-10-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='user_id',
        ),
    ]
